/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_rovkinmax_blob_CvPoint2D */

#ifndef _Included_ru_rovkinmax_blob_CvPoint2D
#define _Included_ru_rovkinmax_blob_CvPoint2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_rovkinmax_blob_CvPoint2D
 * Method:    getX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_rovkinmax_blob_CvPoint2D_getX
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvPoint2D
 * Method:    getY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_rovkinmax_blob_CvPoint2D_getY
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
