/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_rovkinmax_blob_CvTrack */

#ifndef _Included_ru_rovkinmax_blob_CvTrack
#define _Included_ru_rovkinmax_blob_CvTrack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getId
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getLabel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getLabel
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getMinX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getMinX
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getMaxX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getMaxX
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getMinY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getMinY
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getMaxY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getMaxY
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getLifetime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getLifetime
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getActive
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getInactive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_rovkinmax_blob_CvTrack_getInactive
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_CvTrack
 * Method:    getCentroid
 * Signature: ()Lru/rovkinmax/blob/CvPoint2D;
 */
JNIEXPORT jobject JNICALL Java_ru_rovkinmax_blob_CvTrack_getCentroid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
