/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ru_rovkinmax_blob_PBASAlgo.h"
/* Header for class ru_rovkinmax_blob_BlobAlgo */

#ifndef _Included_ru_rovkinmax_blob_BlobAlgo
#define _Included_ru_rovkinmax_blob_BlobAlgo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_rovkinmax_blob_BlobAlgo
 * Method:    n_process
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ru_rovkinmax_blob_BlobAlgo_n_1process
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_rovkinmax_blob_BlobAlgo
 * Method:    getTracks
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_ru_rovkinmax_blob_BlobAlgo_getTracks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
