/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_rovkinmax_blob_PBASAlgo */

#ifndef _Included_ru_rovkinmax_blob_PBASAlgo
#define _Included_ru_rovkinmax_blob_PBASAlgo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    newInitialization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_newInitialization
  (JNIEnv *, jobject);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    n_processImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ru_rovkinmax_blob_PBASAlgo_n_1processImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setN
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setRauteMin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setRauteMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setRLower
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setRLower
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setRIncDec
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setRIncDec
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setRScale
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setRScale
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setTInit
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setTInit
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setTLower
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setTLower
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setTUpper
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setTUpper
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setTDec
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setTDec
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ru_rovkinmax_blob_PBASAlgo
 * Method:    setTInc
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ru_rovkinmax_blob_PBASAlgo_setTInc
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
